baseURL = "https://ignasius-jpeg.github.io/RadixArk-blog-test/"
languageCode = "en-us"
title = "RadixArk Blog"
publishDir = "docs"

[params]
  brand = "RadixArk"
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


